consulting/urls.py
from django.urls import path

from consulting import views

app_name = 'consulting'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('news/', views.NewsListView.as_view(), name='news-list'),
    path('news/<str:slug>/', views.NewsDetailView.as_view(), name='news-detail'),
    path('news/category/<str:slug>/', views.CategoryNewsView.as_view(), name='category-news-list'),
    path('search-news/', views.NewsSearchView.as_view(), name='news-search'),
    path('programs/', views.ProgramListView.as_view(), name='program-list'),
    path('programs/<str:slug>/', views.ProgramDetailView.as_view(), name='program-detail'),
    path('programs/category/<str:slug>/', views.CategoryProgramView.as_view(), name='category-program-list'),
    path('search-programs/', views.ProgramSearchView.as_view(), name='program-search'),
    path('students/', views.StudentListView.as_view(), name='student-list'),
    path('students/<str:slug>/', views.StudentDetailView.as_view(), name='student-detail'),
    path('students/<int:pk>/comment/', views.StudentCommentView.as_view(), name='student-comment'),
    path('comment/<int:pk>/', views.AddCommentView.as_view(), name='comment'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

flymir/urls.py
from django.contrib import admin
import debug_toolbar
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('consulting.urls', namespace='consulting')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

templates/blog-grid.html
{% extends 'inner-base.html' %}
{% load static %}
{% block content %}

        <div id="content" class="site-content" style="margin-top: -200px;">
        <div class="page-header dtable text-center header-transparent pheader-about">
            <div class="dcell">
                <div class="container">
                    <h1 class="page-title" style="color: black;">News</h1>
                </div>
            </div>
        </div>
    </div>

        <div class="entry-content">
            <div class="container">
                <div class="row">
                  {% for news in page_obj %}
                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <div class="post-box masonry-post post-item">
                            <div class="post-inner">
                                <div class="entry-media post-cat-abs">
                                    <a href="{% url 'consulting:news-detail' news.slug %}"><img src="{{news.home_image.url}}" alt=""></a>
                                    <div class="post-cat">
                                        <div class="posted-in"><a href="{{news.category.get_absolute_url}}">{{news.category.name}}</a></div>
                                    </div>
                                </div>
                                <div class="inner-post">
                                    <div class="entry-header">
                                        <div class="entry-meta">
                                            <span class="posted-on"><a href="{% url 'consulting:news-detail' news.slug %}">{{news.date}}</a></span>
                                            <span class="byline">
                                                <span class="author vcard"><a class="url fn n" href="#">{{news.author}}</a></span>
                                            </span>
                                        </div><!-- .entry-meta -->

                                        <h5 class="entry-title">
                                            <a class="title-link" href="{{news.get_absolute_url}}">{{news.name}}</a>
                                        </h5>
                                    </div><!-- .entry-header -->

                                    <div class="the-excerpt">
                                        {{news.text|safe|truncatewords:10}}
                                    </div><!-- .entry-content -->
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% if page_obj.paginator %}
                {% if page_obj.has_next or page_obj.has_previous%}
                <ul class="page-pagination text-center mt-3 none-style">

                  {% if page_obj.has_previous %}
                    <li><a class="prev page-numbers" href="?page={{page_obj.previous_page_number}}">Prev</a></li>
                    {% else %}

                    {% endif %}

                    {% for page in page_obj.paginator.page_range %}
                    {% if page_obj.number == page %}
                    <li class="active"><span>{{page}} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                    <li><a href="?page={{page}}">{{page}}</a></li>
                    {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li><a class="next page-numbers" href="?page={{page_obj.next_page_number}}">Next</a></li>
                    {% else %}

                    {% endif %}

                </ul>
                {% else %}
                <div></div>
                {% endif %}
                {% endif %}
            </div>
        </div>

{% endblock %}

templates/news-category.html
{% extends 'inner-base.html' %}
{% load static %}
{% block content %}

    <div id="content" class="site-content" style="margin-top: -200px;">
        <div class="page-header dtable text-center header-transparent pheader-about">
            <div class="dcell">
                <div class="container">
                    <h1 class="page-title" style="color: black;">{{category.name}} News</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="entry-content" style="margin-top: -150px;">
        <div class="container">
            <div class="row">
                {% for news in page_obj %}
                <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="post-box masonry-post post-item">
                        <div class="post-inner">
                            <div class="entry-media post-cat-abs">
                                <a href="{% url 'consulting:news-detail' news.slug %}"><img src="{{news.image.url}}" alt=""></a>
                                <div class="post-cat">
                                    <div class="posted-in"><a href="{% url 'consulting:category-news-list' news.category.slug %}">{{news.category.name}}</a></div>
                                </div>
                            </div>
                            <div class="inner-post">
                                <div class="entry-header">
                                    <div class="entry-meta">
                                        <span class="posted-on"><a href="{% url 'consulting:news-detail' news.slug %}">{{news.date}}</a></span>
                                        <span class="byline">
                                            <span class="author vcard"><a class="url fn n" href="{% url 'consulting:news-detail' news.slug %}">{{news.author}}</a></span>
                                        </span>
                                    </div><!-- .entry-meta -->

                                    <h5 class="entry-title">
                                        <a class="title-link" href="{% url 'consulting:news-detail' news.slug %}">{{news.name}}</a>
                                    </h5>
                                </div><!-- .entry-header -->

                                <div class="the-excerpt">
                                    {{news.description|truncatewords:15}}
                                </div><!-- .entry-content -->
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% if page_obj.paginator %}
            {% if page_obj.has_next or page_obj.has_previous %}
            <ul class="page-pagination text-center mt-3 none-style">

                {% if page_obj.has_previous %}
                <li><a class="prev page-numbers" href="?page={{page_obj.previous_page_number}}">Prev</a></li>
                {% else %}

                {% endif %}

                {% for page in page_obj.paginator.page_range %}
                {% if page_obj.number == page %}
                <li class="active"><span>{{page}} <span class="sr-only">(current)</span></span></li>
                {% else %}
                <li><a href="?page={{page}}">{{page}}</a></li>
                {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                <li><a class="next page-numbers" href="?page={{page_obj.next_page_number}}">Next</a></li>
                {% else %}

                {% endif %}

            </ul>
            {% else %}
            <div></div>
            {% endif %}
            {% endif %}
        </div>
    </div>

    {% endblock %}

templates/news-detail.html
{% extends 'inner-base.html' %}
{% load static %}
{% block content %}

    <div class="entry-content">
        <div class="container">
            <div class="row">
                <div class="content-area col-lg-9 col-md-12 col-sm-12 col-xs-12">
                    <article class="blog-post post-box">

                        <div class="inner-post">
                            <header class="entry-header">
                                <h3 class="entry-title">{{news.name}}</h3>
                            </header>
                            <div class="entry-meta">
                                <span class="byline" style="font-size:17px;"><a class="url fn n" href="javascript:void(0);">{{news.description}}</a></span>
                            </div>
                            <div class="entry-media post-cat-abs">
                                <img src="{{news.image.url}}" alt="">

                                <div class="post-cat">
                                    <div class="posted-in"><a href="{% url 'consulting:category-news-list' news.category.slug %}">{{news.category.name}}</a></div>
                                </div>
                            </div>
                            <div class="entry-meta">
                                <span class="byline"><a class="url fn n" href="javascript:void(0);">{{news.author}}</a></span>
                                <span class="posted-on"> <a href="javascript:void(0);">{{news.date}}</a></span>
                                <span class="comment-num"> <a href="javascript:void(0);">{{news.comment_count}} Comments</a></span>
                            </div>
                            <div class="entry-summary the-excerpt">
                                <p>{{news.text|safe}}</p>
                            </div>
                            <div class="entry-footer clearfix">
                                {% for category in categories %}
                                {% if category.count > 0 %}
                                <div class="tagcloud" style="padding-right: 15px;">
                                    <a href="{% url 'consulting:category-news-list' category.slug %}" rel="tag">{{category.name}}</a>
                                </div>
                                {% endif %}
                                {% endfor %}
                            </div>
                            {% if related_news %}
                            <div class="related-posts">
                                <h3>Related Posts</h3>
                                <div class="row">
                                    {% for news in related_news %}
                                    <div class="col-lg-6 col-md-6 col-sm">
                                        <div class="post-box post-item">
                                            <div class="post-inner">
                                                <div class="entry-media post-cat-abs">
                                                    <a href="{% url 'consulting:news-detail' news.slug %}"><img src="{{news.image.url}}" alt=""></a>
                                                    <div class="post-cat">
                                                        <div class="posted-in"><a href="{% url 'consulting:category-news-list' news.category.slug %}">{{news.category.name}}</a></div>
                                                    </div>
                                                </div>
                                                <div class="inner-post">
                                                    <div class="entry-header">
                                                        <div class="entry-meta">
                                                            <span class="posted-on"><a href="{% url 'consulting:news-detail' news.slug %}">{{news.date}}</a></span>
                                                            <span class="byline">
                                                                <span class="author vcard"><a class="url fn n" href="{% url 'consulting:news-detail' news.slug %}">{{news.author}}</a></span>
                                                            </span>
                                                        </div><!-- .entry-meta -->

                                                        <h5 class="entry-title">
                                                            <a class="title-link" href="{% url 'consulting:news-detail' news.slug %}">{{news.name}}</a>
                                                        </h5>
                                                    </div><!-- .entry-header -->

                                                    <div class="the-excerpt">
                                                        {{news.description|truncatewords:15}}
                                                    </div><!-- .entry-content -->
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    </article>

                    {% if news.comments.all %}
                    <div id="comments" class="comments-area">
                        <h3 class="comments-title">Comments <span>({{news.comment_count}})</span></h3>

                        {% for comment in news.comments.all|slice:":10" %}

                        <ol class="comment-list">
                            <li class="comment even thread-even comment-item">
                                <article class="comment-wrap clearfix" style="margin-left:-75px;">
                                    <div class="comment-content">
                                        <div class="comment-meta">
                                            <h6 class="comment-author">{{comment.name}}</h6>
                                            <span class="comment-time">{{comment.date}}</span>
                                            <div class="comment-reply"><a class="comment-reply-link" href="#formReview"
                                                onclick="AddReview('{{comment.name}}', '{{comment.id}}')"
                                            >Reply</a></div>
                                        </div>
                                        <div class="comment-text">
                                            <p>{{comment.message}}</p>
                                        </div>
                                    </div>
                                </article>
                            </li>
                        </ol>
                        {% endfor %}
                    </div>
                    {% endif %}

                    <script>
                    function AddReview(name, id) {
                        document.getElementById('contactparent').value = id;
                        document.getElementById('comment').innerHTML = `${name}, `;
                        console.log(id);
                        console.log(name);
                    }
                    </script>
                    <div class="comment-respond">
                        <h3 class="comment-reply-title" id="formReview">Leave a comment</h3>
                        <form action="{% url 'consulting:comment' news.pk %}" method="POST" class="comment-form">
                            {% csrf_token %}
                            <p class="comment-notes"> All fields are required <span class="required">*</span></p>
                            <div class="row">
                                <p class="comment-form-author col-md-12">
                                    <input id="author" name="name" type="text" value="" size="30" placeholder="Name*" required="">
                                </p>
                                <input type="hidden" name="parent" id="contactparent" value="">
                            </div>
                            <p class="comment-form-comment">
                                <textarea id="comment" name="message" cols="45" rows="8" placeholder="Comment*" required=""></textarea>
                            </p>
                            <p class="form-submit">
                                <input name="submit" type="submit" id="submit" class="octf-btn" value="Post Comment">
                            </p>
                        </form>
                    </div>
                </div>
                <div class="widget-area primary-sidebar col-lg-3 col-md-12 col-sm-12 col-xs-12">
                    <aside id="search-2" class="widget widget_search">
                        <form role="search" action="{% url 'consulting:news-search' %}" method="get" class="search-form">
                            <input type="search" class="search-field" placeholder="Search..." value="" name="search">
                            <button type="submit" class="search-submit"><i class="ot-flaticon-search"></i></button>
                        </form>
                    </aside>

                    {% if categories %}
                    <aside class="widget widget_categories">
                        <h6 class="widget-title">Categories</h6>
                        <ul>
                            {% for category in categories %}
                            {% if category.count > 0 %}
                            <li><a href="{% url 'consulting:category-news-list' category.slug %}">{{category.name}}</a> <span class="count">({{category.count}})</span></li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </aside>
                    {% endif %}

                    {% if recent_news %}
                    <aside class="widget widget_recent_news">
                        <h6 class="widget-title">Recent Posts</h6>
                        <ul class="recent-news clearfix">
                            {% for news in recent_news %}
                            <li class="clearfix">
                                <div class="thumb">
                                    <a href="{% url 'consulting:news-detail' news.slug %}"><img src="{{news.image.url}}" alt=""></a>
                                </div>
                                <div class="entry-header">
                                    <h6><a href="{% url 'consulting:news-detail' news.slug %}">{{news.name|truncatewords:7}}</a></h6>
                                    <span class="post-on"><span class="entry-date">{{news.date}}</span></span>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </aside>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    {% endblock %}

templates/student-detail.html
{% extends 'inner-base.html' %}
{% load static %}
{% block content %}

    <div id="content" class="site-content" style="margin-top: -200px;">
        <div class="page-header dtable text-center header-transparent pheader-about">
            <div class="dcell">
                <div class="container">
                    <h1 class="page-title" style="color: black;">{{student.name}}</h1>
                </div>
            </div>
        </div>
    </div>

    <section class="portfolio-detail p-0" {% if not students %} style="margin-top: -150px; margin-bottom: 100px;" {% else %} style="margin-top: -150px;" {% endif %}>
        <div class="container">
            <div class="row">
                <div class="space-90"></div>
                <div class="col-lg-6 col-md-12">
                    <h4>How was the process?</h4>
                    <p><span class="drop-cap"><span class="drop-cap-letter"></span></span>{{student.text|safe}}</p>
                    <div class="space-20"></div>
                    <div class="space-5"></div>
                    <div class="row">
                        <div class="col-md-4 col-sm-6 col-6">
                            <div class="p-detail-info">
                                <h6>Organisation:</h6>
                                <p>Fly Mir Consulting</p>
                            </div>
                            <div class="space-20"></div>
                        </div>
                        <div class="col-md-4 col-sm-6 col-6">
                            <div class="p-detail-info">
                                <h6>Client:</h6>
                                <p>{{student.name}}</p>
                            </div>
                            <div class="space-20"></div>
                        </div>
                        <div class="col-md-4 col-sm-6 col-6">
                            <div class="p-detail-info">
                                <h6>Country:</h6>
                                <p>{{student.country.name}}</p>
                            </div>
                            <div class="space-20"></div>
                        </div>
                        <div class="col-md-4 col-sm-6 col-6">
                            <div class="p-detail-info">
                                <h6>University:</h6>
                                <p>{{student.university.name}}</p>
                            </div>
                            <div class="space-20"></div>
                        </div>
                        <div class="col-md-4 col-sm-6 col-6">
                            <div class="p-detail-info">
                                <h6>Program:</h6>
                                <p>{{student.program_type}}</p>
                            </div>
                            <div class="space-20"></div>
                        </div>
                        <div class="col-md-4 col-sm-6 col-6">
                            <div class="p-detail-info">
                                <h6>Date:</h6>
                                <p>{{student.date}}</p>
                            </div>
                            <div class="space-20"></div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-6 col-md-12 mb-5 mb-lg-0">
                    <div class="image-gallery">
                        <div id="gallery-2" class="gallery gallery-columns-1 s2">
                            <figure class="gallery-item">
                                <div class="gallery-icon portrait">
                                    <a href="{{student.image.url}}">
                                        <img src="{{student.image.url}}" alt="">
                                        <span class="overlay"><i class="ot-flaticon-add"></i></span>
                                    </a>
                                </div>
                            </figure>
                        </div>
                    </div>
                </div>
            </div>

            {% if student.comments.all %}
            <section class="about-testi">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 text-center theratio-align-center">
                            <div class="ot-heading">
                                <span>[ testimonials ]</span>
                                <h2 class="main-heading">What Students Say</h2>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="ot-testimonials v-light">
                                <div class="testimonial-inner testi-col-3 owl-theme owl-carousel">
                                    {% for comment in student.comments.all %}
                                    <div class="testi-item">
                                        <div class="ttext">
                                            <div class="layer-behind"></div>
                                            <span></span>
                                            {{comment.message|truncatewords:50}}
                                        </div>
                                        <div class="t-head flex-middle">
                                            <div class="tinfo">
                                                <h6>{{comment.name}}</h6>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            {% endif %}

            <script>
            function AddReview(name, id) {
                document.getElementById('contactparent').value = id;
                document.getElementById('comment').innerHTML = `${name}, `;
                console.log(id);
                console.log(name);
            }
            </script>
            <div class="comment-respond" style="margin-top: 100px; margin-bottom: 100px;">
                <h3 class="comment-reply-title" id="formReview">Leave a comment</h3>
                <form action="{% url 'consulting:student-comment' student.pk %}" method="POST" class="comment-form">
                    {% csrf_token %}
                    <p class="comment-notes"> All fields are required <span class="required">*</span></p>
                    <div class="row">
                        <p class="comment-form-author col-md-12">
                            <input id="author" name="name" type="text" value="" size="30" placeholder="Name*" required="">
                        </p>
                        <input type="hidden" name="parent" id="contactparent" value="">
                    </div>
                    <p class="comment-form-comment">
                        <textarea id="comment" name="message" cols="45" rows="8" placeholder="Comment*" required=""></textarea>
                    </p>
                    <p class="form-submit">
                        <input name="submit" type="submit" id="submit" class="octf-btn" value="Post Comment">
                    </p>
                </form>
            </div>
        </div>
    </section>

    {% endblock %}